
#--------------------------------------<  General  >------------------------------------------------
stages:
  - build
  - test
  - sonarqube
  # TODO: - pack

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# keep the npm cache around to speed up installs
cache:
  paths:
    - $CI_PROJECT_DIR/.npm
    - $CI_PROJECT_DIR/node_modules
    - .kaniko

#---------------------------------------<  Builder  >-------------------------------------------------
#
# This job will build and push a docker image used by next steps.
# when: triggered when a tag "builder-vX.Y.Z" is added
# the version (X.Y.Z) is extracted and used to push the docker image.
#
build builder:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  rules:
    # expect a tag like: "builder-vX.Y.Z"
    - if: $CI_COMMIT_TAG =~ /^builder-v\d+.\d+.\d+$/
      when: always
    - when: never

  before_script:
    # Setup docker authentication file
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
  script:
    # remove 'builder-v' prefix
    - BUILDER_VERSION=`echo ${CI_COMMIT_TAG//builder-v/}`
    - mkdir -p .kaniko

    # build and push docker
    - cd docker/builder
    - DOCKER_TAG=$DOCKER_REPOSITORY/builder:$BUILDER_VERSION
    - /kaniko/executor --cache-dir=.kaniko --context ./ --dockerfile ./Dockerfile --destination $DOCKER_TAG

#------------------------------<  Base job to be extended  >----------------------------------------
.base-job:
  image: $DOCKER_REPOSITORY/builder:$BUILDER_VERSION
  before_script:
    - npm config set cache $CI_PROJECT_DIR/.npm --global
  only:
    refs:
      - master
      - merge_requests

#---------------------------------------<  Build  >-------------------------------------------------
build:
  extends: .base-job
  stage: build
  script:
    - npm ci
    - npx --package=@ionic/cli ionic cordova build android --prod

  artifacts:
    paths:
      - $CI_PROJECT_DIR/platforms/android
      - $CI_PROJECT_DIR/build

#---------------------------------------<  Test  >--------------------------------------------------
test:
  extends: .base-job
  stage: test
  script:
    - npm run test:ci
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage

#---------------------------------------<  Sonar qube  >--------------------------------------------------
sonarqube:
  image: sonarsource/sonar-scanner-cli
  stage: sonarqube
  script:
    - cat $SONAR_PROPERTIES_FILE > sonar-project.properties
    - sonar-scanner $SONAR_ADDITIONNAL_ARGS
  only:
    refs:
      - master # our licence only allows us to use a single branch (so it is master)

#---------------------------------------<  Prod  >-------------------------------------------------
#
# This job will build the apk and sign it
# when: triggered when a tag "X.Y.Z" is added
# the version (X.Y.Z) is extracted and used to name the files
#
build_prod:
  stage: build
  image: $DOCKER_REPOSITORY/builder:$BUILDER_VERSION
  rules:
    # expect a tag like: "X.Y.Z"
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/
      when: always
    - when: never

  before_script:
    - npm config set cache $CI_PROJECT_DIR/.npm --global
  script:
    - npm ci
    - npx --package=@ionic/cli ionic cordova platform rm android
    - npx --package=@ionic/cli ionic cordova platform add android
    - npx --package=@ionic/cli ionic cordova build android --prod --release -- -- --packageType=apk
    - npx --package=@ionic/cli ionic cordova build android --prod --release -- -- --packageType=bundle
    - zipalign -v -f 4 ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk sirsmobile_$CI_COMMIT_TAG.apk
    - zipalign -v -f 4 ./platforms/android/app/build/outputs/bundle/release/app-release.aab sirsmobile_$CI_COMMIT_TAG.aab
    - apksigner sign --ks sirs-mobile.keystore --ks-pass "pass:$KEYSTORE_PASS" --v1-signing-enabled true --v2-signing-enabled true sirsmobile_$CI_COMMIT_TAG.apk
    - apksigner sign --ks sirs-mobile.keystore --ks-pass "pass:$KEYSTORE_PASS" --v1-signing-enabled true --v2-signing-enabled true --min-sdk-version 26 sirsmobile_$CI_COMMIT_TAG.aab

  artifacts:
    paths:
      - sirsmobile_$CI_COMMIT_TAG.apk
      - sirsmobile_$CI_COMMIT_TAG.aab
    when: on_success
    name: sirsmobile_$CI_COMMIT_TAG
    expire_in: never
